name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: ./deploy.ps1
        shell: pwsh
        env:
          SP_SECRET: ${{ secrets.SP_SECRET }}
          SP_CLIENT: "dd082b18-ec0f-43b5-94da-dcb9da0714d0"
          SP_TENANT: "72f988bf-86f1-41af-91ab-2d7cd011db47"
          APP_GROUP: "github-experts"
          APP_NAME: "githubexperts"
          B2C_CLIENT_ID: "144e9bd1-f04e-4454-abc6-1dae3af35cc4"
          B2C_TENANT_NAME: "h3dev"
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
          GITHUB_APP_NAME: "githubapp"
          GITHUB_APP_ID: "74517"
          GITHUB_CLIENT_ID: "Iv1.f5fa489caf10b58a"
          GITHUB_CLIENT_SECRET: "c3c6a7be3bda54c42f7847914d38471fd6272c7f"
